
import java.util.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Examen1LabP2 extends javax.swing.JFrame {

  // Variables Globales
  public static Scanner entry = new Scanner(System.in);
  // Mis Variables
  private static ArrayList<PC> computadoras = new ArrayList();

  /**
   * Creates new form Examen1LabP2
   */
  public Examen1LabP2() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jTabbedPane1 = new javax.swing.JTabbedPane();
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    ingresarPcBtn = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    jLabel5 = new javax.swing.JLabel();
    jTabbedPane2 = new javax.swing.JTabbedPane();
    jPanel5 = new javax.swing.JPanel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    jTextField_EscritorioMasRed = new javax.swing.JTextField();
    jTextField_EscritorioHostname = new javax.swing.JTextField();
    jTextField_EscritorioIP = new javax.swing.JTextField();
    jTextField_EscritorioRam = new javax.swing.JTextField();
    jTextField_EscritorioAlmacenamiento = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    jList_TipoAlmacenamiento = new javax.swing.JList<>();
    jLabel12 = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    jList_EscritorioGrafica = new javax.swing.JList<>();
    EscritorioBtn = new javax.swing.JButton();
    jPanel6 = new javax.swing.JPanel();
    jPanel7 = new javax.swing.JPanel();
    jLabel13 = new javax.swing.JLabel();
    jLabel14 = new javax.swing.JLabel();
    jLabel15 = new javax.swing.JLabel();
    jLabel16 = new javax.swing.JLabel();
    jLabel17 = new javax.swing.JLabel();
    jTextField_LaptopMasRed = new javax.swing.JTextField();
    jTextField_LaptopHostname = new javax.swing.JTextField();
    jTextField_LaptopIP = new javax.swing.JTextField();
    jTextField_LaptopMarca = new javax.swing.JTextField();
    jTextField_LaptopDefPantalla = new javax.swing.JTextField();
    jLabel19 = new javax.swing.JLabel();
    jScrollPane4 = new javax.swing.JScrollPane();
    jList_LaptopRGB = new javax.swing.JList<>();
    laptopBtn = new javax.swing.JButton();
    jPanel3 = new javax.swing.JPanel();
    jLabel_ListarEmpty = new javax.swing.JLabel();
    jLabel_ListarPcTitle1 = new javax.swing.JLabel();
    jScrollPane3 = new javax.swing.JScrollPane();
    jTextArea_Listas = new javax.swing.JTextArea();
    jPanel4 = new javax.swing.JPanel();
    jLabel_BorrarEmpty = new javax.swing.JLabel();
    jLabel_BorrarPcs = new javax.swing.JLabel();
    jScrollPane5 = new javax.swing.JScrollPane();
    jTextArea_Listas1 = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setBackground(new java.awt.Color(233, 248, 249));
    setResizable(false);
    setSize(new java.awt.Dimension(595, 455));

    jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jTabbedPane1MouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        jTabbedPane1MouseEntered(evt);
      }
    });

    jPanel1.setBackground(new java.awt.Color(233, 248, 249));

    jLabel1.setBackground(new java.awt.Color(24, 24, 35));
    jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
    jLabel1.setText("Bienvenido al programa de Redes de Telecomunicaciones");

    jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
    jLabel2.setText("En este programa podrás agregar PCs con su respectiva información, listarlas, y eliminarlas.");

    jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
    jLabel3.setText("En esta versión consola, podrás ingresar los comandos disponibles para la computadora");

    jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
    jLabel4.setText("También tienes la opción de ingresar a una PC, y luego entrar a su versión en consola. ");

    ingresarPcBtn.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
    ingresarPcBtn.setText("INGRESAR A PC");
    ingresarPcBtn.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        ingresarPcBtnMouseClicked(evt);
      }
    });
    ingresarPcBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ingresarPcBtnActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
              .addComponent(ingresarPcBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel2)))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(6, 6, 6)
            .addComponent(jLabel4))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(6, 6, 6)
            .addComponent(jLabel3))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(6, 6, 6)
            .addComponent(jLabel1)))
        .addContainerGap(90, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(29, 29, 29)
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jLabel4)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel3)
        .addGap(18, 18, 18)
        .addComponent(ingresarPcBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(165, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Bienvenido", jPanel1);

    jPanel2.setBackground(new java.awt.Color(233, 248, 249));

    jLabel5.setBackground(new java.awt.Color(24, 24, 35));
    jLabel5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
    jLabel5.setText("Agrega una nueva PC");

    jPanel5.setBackground(new java.awt.Color(233, 248, 249));

    jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
    jLabel6.setText("Ingrese la dirección IP: ");

    jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
    jLabel7.setText("Ingrese la mascara de la Red: ");

    jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
    jLabel8.setText("Ingrese el hostname: ");

    jLabel9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
    jLabel9.setText("Ingrese la capacidad de RAM: ");

    jLabel10.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
    jLabel10.setText("Ingrese la capacidad de Almacenamiento: ");

    jLabel11.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
    jLabel11.setText("Seleccione el tipo de Almacenamiento");

    jTextField_EscritorioMasRed.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField_EscritorioMasRedActionPerformed(evt);
      }
    });

    jTextField_EscritorioHostname.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField_EscritorioHostnameActionPerformed(evt);
      }
    });

    jTextField_EscritorioIP.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField_EscritorioIPActionPerformed(evt);
      }
    });

    jTextField_EscritorioRam.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField_EscritorioRamActionPerformed(evt);
      }
    });

    jTextField_EscritorioAlmacenamiento.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField_EscritorioAlmacenamientoActionPerformed(evt);
      }
    });

    jList_TipoAlmacenamiento.setModel(new javax.swing.AbstractListModel<String>() {
      String[] strings = { "HDD", "SSD" };
      public int getSize() { return strings.length; }
      public String getElementAt(int i) { return strings[i]; }
    });
    jList_TipoAlmacenamiento.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jScrollPane1.setViewportView(jList_TipoAlmacenamiento);

    jLabel12.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
    jLabel12.setText("¿Tiene tarjeta gráfica?");

    jList_EscritorioGrafica.setModel(new javax.swing.AbstractListModel<String>() {
      String[] strings = { "Si", "No" };
      public int getSize() { return strings.length; }
      public String getElementAt(int i) { return strings[i]; }
    });
    jList_EscritorioGrafica.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jScrollPane2.setViewportView(jList_EscritorioGrafica);

    EscritorioBtn.setText("Agregar PC de Escritorio");
    EscritorioBtn.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        EscritorioBtnMouseClicked(evt);
      }
    });
    EscritorioBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        EscritorioBtnActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel5Layout.createSequentialGroup()
        .addContainerGap(79, Short.MAX_VALUE)
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
            .addComponent(jLabel8)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jTextField_EscritorioHostname, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
            .addComponent(jLabel6)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jTextField_EscritorioIP, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
            .addComponent(jLabel7)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jTextField_EscritorioMasRed, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
            .addComponent(jLabel9)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jTextField_EscritorioRam, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGap(18, 18, 18)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jTextField_EscritorioAlmacenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap())
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(EscritorioBtn)
        .addGap(236, 236, 236))
    );
    jPanel5Layout.setVerticalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel5Layout.createSequentialGroup()
        .addGap(11, 11, 11)
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel6)
          .addComponent(jTextField_EscritorioIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(9, 9, 9)
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jTextField_EscritorioMasRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel7))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jTextField_EscritorioHostname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel8))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel9)
          .addComponent(jTextField_EscritorioRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jTextField_EscritorioAlmacenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel10))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel11))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel12)
          .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(EscritorioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    jTabbedPane2.addTab("PC de Escritorio", jPanel5);

    jPanel6.setBackground(new java.awt.Color(233, 248, 249));

    jPanel7.setBackground(new java.awt.Color(233, 248, 249));

    jLabel13.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
    jLabel13.setText("Ingrese la dirección IP: ");

    jLabel14.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
    jLabel14.setText("Ingrese la mascara de la Red: ");

    jLabel15.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
    jLabel15.setText("Ingrese el hostname: ");

    jLabel16.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
    jLabel16.setText("Ingrese la marca de la laptop:");

    jLabel17.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
    jLabel17.setText("Ingrese la resolución de la pantalla: ");

    jTextField_LaptopMasRed.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField_LaptopMasRedActionPerformed(evt);
      }
    });

    jTextField_LaptopHostname.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField_LaptopHostnameActionPerformed(evt);
      }
    });

    jTextField_LaptopIP.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField_LaptopIPActionPerformed(evt);
      }
    });

    jTextField_LaptopMarca.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField_LaptopMarcaActionPerformed(evt);
      }
    });

    jTextField_LaptopDefPantalla.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField_LaptopDefPantallaActionPerformed(evt);
      }
    });

    jLabel19.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
    jLabel19.setText("¿Tiene RGB en el teclado?");

    jList_LaptopRGB.setModel(new javax.swing.AbstractListModel<String>() {
      String[] strings = { "Si", "No" };
      public int getSize() { return strings.length; }
      public String getElementAt(int i) { return strings[i]; }
    });
    jList_LaptopRGB.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jScrollPane4.setViewportView(jList_LaptopRGB);

    laptopBtn.setText("Agregar Laptop");
    laptopBtn.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        laptopBtnMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
    jPanel7.setLayout(jPanel7Layout);
    jPanel7Layout.setHorizontalGroup(
      jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel7Layout.createSequentialGroup()
        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_LaptopHostname, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_LaptopIP, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_LaptopMasRed, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_LaptopMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))
          .addGroup(jPanel7Layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jLabel17)
              .addComponent(jLabel19))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField_LaptopDefPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)))))
        .addContainerGap())
      .addGroup(jPanel7Layout.createSequentialGroup()
        .addGap(187, 187, 187)
        .addComponent(laptopBtn)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel7Layout.setVerticalGroup(
      jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel7Layout.createSequentialGroup()
        .addGap(11, 11, 11)
        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel13)
          .addComponent(jTextField_LaptopIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(9, 9, 9)
        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jTextField_LaptopMasRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel14))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel15)
          .addComponent(jTextField_LaptopHostname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel16)
          .addComponent(jTextField_LaptopMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel17)
          .addComponent(jTextField_LaptopDefPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel19))
        .addGap(18, 18, 18)
        .addComponent(laptopBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(44, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
      jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 652, Short.MAX_VALUE)
      .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
          .addGap(0, 0, Short.MAX_VALUE)
          .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(0, 0, Short.MAX_VALUE)))
    );
    jPanel6Layout.setVerticalGroup(
      jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 318, Short.MAX_VALUE)
      .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
          .addGap(0, 0, Short.MAX_VALUE)
          .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(0, 0, Short.MAX_VALUE)))
    );

    jTabbedPane2.addTab("Laptop", jPanel6);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jTabbedPane2)
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(jLabel5)
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jTabbedPane2)
        .addContainerGap())
    );

    jTabbedPane1.addTab("Agregar PC", jPanel2);

    jPanel3.setBackground(new java.awt.Color(233, 248, 249));
    jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        jPanel3MouseEntered(evt);
      }
    });

    jLabel_ListarEmpty.setBackground(new java.awt.Color(24, 24, 35));
    jLabel_ListarEmpty.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
    jLabel_ListarEmpty.setText("No hay PCs o Laptops Disponibles");

    jLabel_ListarPcTitle1.setBackground(new java.awt.Color(24, 24, 35));
    jLabel_ListarPcTitle1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
    jLabel_ListarPcTitle1.setText("Estas son las PCs Disponibles");

    jTextArea_Listas.setBackground(new java.awt.Color(192, 238, 242));
    jTextArea_Listas.setColumns(20);
    jTextArea_Listas.setRows(5);
    jScrollPane3.setViewportView(jTextArea_Listas);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGap(154, 154, 154)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel_ListarPcTitle1)
          .addComponent(jLabel_ListarEmpty))
        .addContainerGap(235, Short.MAX_VALUE))
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane3)
        .addContainerGap())
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGap(42, 42, 42)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel_ListarPcTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel_ListarEmpty, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
        .addContainerGap())
    );

    jTabbedPane1.addTab("Listar PCs", jPanel3);

    jPanel4.setBackground(new java.awt.Color(233, 248, 249));

    jLabel_BorrarEmpty.setBackground(new java.awt.Color(24, 24, 35));
    jLabel_BorrarEmpty.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
    jLabel_BorrarEmpty.setText("No hay PCs o Laptops disponibles para borrar");

    jLabel_BorrarPcs.setBackground(new java.awt.Color(24, 24, 35));
    jLabel_BorrarPcs.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
    jLabel_BorrarPcs.setText("Seleccione la PC que desea borrar");

    jTextArea_Listas1.setBackground(new java.awt.Color(192, 238, 242));
    jTextArea_Listas1.setColumns(20);
    jTextArea_Listas1.setRows(5);
    jScrollPane5.setViewportView(jTextArea_Listas1);

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel4Layout.createSequentialGroup()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jLabel_BorrarPcs))
              .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel_BorrarEmpty)))
            .addGap(0, 116, Short.MAX_VALUE))
          .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING))
        .addContainerGap())
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addGap(30, 30, 30)
        .addComponent(jLabel_BorrarEmpty, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel_BorrarPcs, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
        .addContainerGap())
    );

    jTabbedPane1.addTab("Eliminar PC", jPanel4);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jTabbedPane1)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void ingresarPcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarPcBtnActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_ingresarPcBtnActionPerformed

  private void ingresarPcBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarPcBtnMouseClicked
    // TODO add your handling code here:
    this.setVisible(false);

    // Call console menu method
    consoleMenu(this);
  }//GEN-LAST:event_ingresarPcBtnMouseClicked

  private void jTextField_EscritorioMasRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EscritorioMasRedActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextField_EscritorioMasRedActionPerformed

  private void jTextField_EscritorioHostnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EscritorioHostnameActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextField_EscritorioHostnameActionPerformed

  private void jTextField_EscritorioIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EscritorioIPActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextField_EscritorioIPActionPerformed

  private void jTextField_EscritorioRamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EscritorioRamActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextField_EscritorioRamActionPerformed

  private void jTextField_EscritorioAlmacenamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EscritorioAlmacenamientoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextField_EscritorioAlmacenamientoActionPerformed

  private void EscritorioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscritorioBtnActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_EscritorioBtnActionPerformed

  // EVENTO PARA CLICK DE BOTON DE AGREGAR PC DE ESCRITORIO
  private void EscritorioBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EscritorioBtnMouseClicked
    // TODO add your handling code here:
    // Declarar variables para crear PC de Escritorio
    String IP = jTextField_EscritorioIP.getText();
    String mascaraRed = jTextField_EscritorioMasRed.getText();
    String hostname = jTextField_EscritorioHostname.getText();
    String capRam = jTextField_EscritorioRam.getText();
    String capAl = jTextField_EscritorioAlmacenamiento.getText();
    String tipoAl = jList_TipoAlmacenamiento.getSelectedValue();
    String hasGraphText = jList_EscritorioGrafica.getSelectedValue();
    boolean hasGraph;

    if (hasGraphText.equalsIgnoreCase("Si")) {
      hasGraph = true;
    } else {
      hasGraph = false;
    }

    // Crear la PC 
    PC pcEscritorio = new PC_Escritorio(capRam, capAl, tipoAl, hasGraph, IP, mascaraRed, hostname);

    JOptionPane.showMessageDialog(this, "¡Pc de Escritorio agregada con Exito!");

    jTextField_EscritorioAlmacenamiento.setText("");
    jTextField_EscritorioHostname.setText("");
    jTextField_EscritorioIP.setText("");
    jTextField_EscritorioMasRed.setText("");
    jTextField_EscritorioRam.setText("");
    jList_TipoAlmacenamiento.setSelectedValue(null, hasGraph);
    jList_EscritorioGrafica.setSelectedValue(null, hasGraph);

    computadoras.add(pcEscritorio);
  }//GEN-LAST:event_EscritorioBtnMouseClicked

  private void jTextField_LaptopMasRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_LaptopMasRedActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextField_LaptopMasRedActionPerformed

  private void jTextField_LaptopHostnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_LaptopHostnameActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextField_LaptopHostnameActionPerformed

  private void jTextField_LaptopMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_LaptopMarcaActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextField_LaptopMarcaActionPerformed

  private void jTextField_LaptopDefPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_LaptopDefPantallaActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextField_LaptopDefPantallaActionPerformed

  private void jTextField_LaptopIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_LaptopIPActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextField_LaptopIPActionPerformed

  // EVENTO PARA CLICK DE BOTON DE AGREGAR LAPTOP
  private void laptopBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laptopBtnMouseClicked
    // TODO add your handling code here:
    String IP = jTextField_LaptopIP.getText();
    String mascaraRed = jTextField_LaptopMasRed.getText();
    String hostname = jTextField_LaptopHostname.getText();
    String marca = jTextField_LaptopMarca.getText();
    String resPantalla = jTextField_LaptopDefPantalla.getText();
    String defMarcaText = jList_LaptopRGB.getSelectedValue();
    boolean hasRgb;

    if (defMarcaText.equalsIgnoreCase("Si")) {
      hasRgb = true;
    } else {
      hasRgb = false;
    }

    // Crear Laptop
    PC laptop = new Laptop(marca, resPantalla, hasRgb, IP, mascaraRed, hostname);

    JOptionPane.showMessageDialog(this, "¡Laptop agregada con Exito!");

    computadoras.add(laptop);
    jTextField_LaptopDefPantalla.setText("");
    jTextField_LaptopHostname.setText("");
    jTextField_LaptopIP.setText("");
    jTextField_LaptopMarca.setText("");
    jTextField_LaptopMasRed.setText("");
    jList_LaptopRGB.setSelectedValue(null, hasRgb);
  }//GEN-LAST:event_laptopBtnMouseClicked


  private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked

  }//GEN-LAST:event_jTabbedPane1MouseClicked

  // Evento para mostrar globalmente las cosas
  private void jTabbedPane1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseEntered
    // TODO add your handling code here:
    if (computadoras.isEmpty()) {
      jLabel_ListarEmpty.setVisible(true);
      jLabel_ListarPcTitle1.setVisible(false);
      jLabel_BorrarEmpty.setVisible(true);
      jLabel_BorrarPcs.setVisible(false);
    } else {
      jLabel_ListarEmpty.setVisible(false);
      jLabel_ListarPcTitle1.setVisible(true);
      jLabel_BorrarEmpty.setVisible(false);
      jLabel_BorrarPcs.setVisible(true);

    }
  }//GEN-LAST:event_jTabbedPane1MouseEntered

  // EVENTO PARA MOSTRAR LAS PCS
  private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
    // TODO add your handling code here:
    if (!computadoras.isEmpty()) {
      for (PC computadora : computadoras) {
        jTextArea_Listas.setText(computadora.toString());
      }
    }
  }//GEN-LAST:event_jPanel3MouseEntered

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Examen1LabP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Examen1LabP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Examen1LabP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Examen1LabP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Examen1LabP2().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton EscritorioBtn;
  private javax.swing.JButton ingresarPcBtn;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel17;
  private javax.swing.JLabel jLabel19;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JLabel jLabel_BorrarEmpty;
  private javax.swing.JLabel jLabel_BorrarPcs;
  private javax.swing.JLabel jLabel_ListarEmpty;
  private javax.swing.JLabel jLabel_ListarPcTitle1;
  private javax.swing.JList<String> jList_EscritorioGrafica;
  private javax.swing.JList<String> jList_LaptopRGB;
  private javax.swing.JList<String> jList_TipoAlmacenamiento;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JPanel jPanel7;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JScrollPane jScrollPane4;
  private javax.swing.JScrollPane jScrollPane5;
  private javax.swing.JTabbedPane jTabbedPane1;
  private javax.swing.JTabbedPane jTabbedPane2;
  private javax.swing.JTextArea jTextArea_Listas;
  private javax.swing.JTextArea jTextArea_Listas1;
  private javax.swing.JTextField jTextField_EscritorioAlmacenamiento;
  private javax.swing.JTextField jTextField_EscritorioHostname;
  private javax.swing.JTextField jTextField_EscritorioIP;
  private javax.swing.JTextField jTextField_EscritorioMasRed;
  private javax.swing.JTextField jTextField_EscritorioRam;
  private javax.swing.JTextField jTextField_LaptopDefPantalla;
  private javax.swing.JTextField jTextField_LaptopHostname;
  private javax.swing.JTextField jTextField_LaptopIP;
  private javax.swing.JTextField jTextField_LaptopMarca;
  private javax.swing.JTextField jTextField_LaptopMasRed;
  private javax.swing.JButton laptopBtn;
  // End of variables declaration//GEN-END:variables

  // Methods of the console menut
  public static void consoleMenu(JFrame pantalla) {
    if (computadoras.isEmpty()) {
      System.out.println("No hay computadoras para ingresar");
      System.out.println("Regresando al menu principal...");
      System.out.println();
      pantalla.setVisible(true);
    } else {
      System.out.println("Bienvenido a la consola de la computadora!");
      System.out.println("--Ingrese compandos para probar la consola--");

      // Seleccionar una computadora de la lista
      PC pcTemporal = computadoras.get(0);
      String hostnamePc = pcTemporal.getHostname();

      do {
        System.out.print(hostnamePc + "#");
        String test = entry.nextLine();

        if (test.equalsIgnoreCase("show")) {
          System.out.println("--Detalles de la computadora en la que te encuentras--");
          System.out.print("La direccion IP es: " + pcTemporal.getIP() + "\n");
          System.out.print("La direccion IP es: " + pcTemporal.getMascaraRed() + "\n");
        }

        if (test.startsWith("ping")) {
          String ping[] = test.split("_");

          System.out.println("Si funciona el metodo Ping");

          // Llamar al metodo ping con la informacion respectiva
          int respuesta = pcTemporal.ping(ping[1], computadoras);

          switch (respuesta) {
            case 1 -> {
              System.out.println();

              System.out.println("Pingin to " + ping[1] + " with 32 bits of data:");
              System.out.println("Reply from " + ping[1] + ": bytes=32 time=37ms TTL=46");
              System.out.println("Reply from " + ping[1] + ": bytes=32 time=37ms TTL=46");
              System.out.println("Reply from " + ping[1] + ": bytes=32 time=37ms TTL=46");
              System.out.println("Reply from " + ping[1] + ": bytes=32 time=37ms TTL=46");

              System.out.println("Ping statistics for " + ping[1] + ":");
              System.out.println("    Packets: sent = 4, Receive = 4, Lost = 0 (100% loss)");
              System.out.println();
            }

            case 2 -> {
              System.out.println();

              System.out.println("Pingin to " + ping[1] + " with 32 bits of data:");
              System.out.println("Reply from " + ping[1] + ": Destination host unreachable");
              System.out.println("Reply from " + ping[1] + ": Destination host unreachable");
              System.out.println("Reply from " + ping[1] + ": Destination host unreachable");
              System.out.println("Reply from " + ping[1] + ": Destination host unreachable");

              System.out.println("Ping statistics for " + ping[1] + ":");
              System.out.println("    Packets: sent = 4, Receive = 0, Lost = 4 (100% loss)");
              System.out.println();
            }

            case 3 -> {
              System.out.println();

              System.out.println("Pingin to " + ping[1] + " with 32 bits of data:");
              System.out.println("Request timed out");
              System.out.println("Request timed out");
              System.out.println("Request timed out");
              System.out.println("Request timed out");

              System.out.println("Ping statistics for " + ping[1] + ":");
              System.out.println("    Packets: sent = 4, Receive = 0, Lost = 4 (100% loss)");
              System.out.println();
            }
          }
        }

        if (test.equalsIgnoreCase("exit")) {
          pantalla.setVisible(true);
          break;
        }
      } while (true);

      System.out.println();
    }
  }
}
